. test XPSDK extractions on all OSes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -71,13 +71,13 @@ jobs:
           echo -e "\nGlobal Variable value for 'global-subversion-text' is: ${{ steps.strings.outputs.global-subversion-text }} "
   
   build-lin:
-    if: ( 1 == 2 )
-    runs-on: ubuntu-22.04
+#    if: ( 1 == 2 )
+    runs-on: ubuntu-24.04
     needs: [pre-build]
     strategy: # Set fail-fast too false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: true
       matrix:
-        os: [ubuntu-22.04]
+        os: [ubuntu-24.04]
         build_type: [ Debug, Release ]
 #        build_type: [ Debug ]
         #build_type: [ Release ]
@@ -209,7 +209,7 @@ jobs:
   
 
   build-osx:
-    if: ( 1 == 2 )
+#    if: ( 1 == 2 )
     runs-on: macos-14
     needs: [pre-build]
     strategy:
@@ -342,8 +342,8 @@ jobs:
       matrix:
         #os: [windows-latest]
         os: [windows-2022]
-#        build_type: [ Debug, Release ]
-        build_type: [Debug]
+        build_type: [ Debug, Release ]
+#        build_type: [Debug]
         c_compiler: [cl]
         cpp_compiler: [cl]
     steps:
@@ -400,10 +400,10 @@ jobs:
           Get-ChildItem -Directory -Name -Recurse
 
 
-      - name: Stop workflow early
-        run: |
-          echo "Stopping here..."
-          exit 1  # Fails the step and halts subsequent steps unless configured otherwise
+#      - name: Stop workflow early
+#        run: |
+#          echo "Stopping here..."
+#          exit 1  # Fails the step and halts subsequent steps unless configured otherwise
         
         
 
